import { 
  ChaoticSystemDefinition, 
  LeveragePoint, 
  AgentProfile, 
  TokenDefinition, 
  DigitalIdentity, 
  SimulationScenario 
} from '../types';

export const mockSystemsData: ChaoticSystemDefinition[] = [
  {
    id: 'financial-market-stability-v1',
    name: 'Global Financial Market Stability',
    description: 'A model of interconnected global financial markets, including indices, commodities, and FX.',
    createdAt: '2023-01-15T10:00:00Z',
    lastModified: '2024-03-10T14:30:00Z',
    ownerId: 'sysadmin-001',
    parameters: [
      {
        id: 'interest-rate-g7',
        name: 'G7 Interest Rate',
        description: 'Average interbank interest rate across G7 nations.',
        currentValue: 4.5,
        unit: '%',
        minValue: 0,
        maxValue: 10,
        step: 0.1,
        isLeverageCandidate: true,
        dataType: 'number',
        securityLevel: 'high',
        governancePolicyId: 'policy-monetary-001',
      },
      {
        id: 'commodity-price-volatility',
        name: 'Global Commodity Price Volatility Index',
        description: 'VIX-like index for major commodities (oil, gold, wheat).',
        currentValue: 25.3,
        unit: 'index points',
        minValue: 5,
        maxValue: 100,
        step: 0.5,
        isLeverageCandidate: false,
        dataType: 'number',
        securityLevel: 'medium',
      },
      {
        id: 'trade-tariff-level',
        name: 'Average Global Trade Tariff Level',
        description: 'Weighted average of tariffs on international trade.',
        currentValue: 3.2,
        unit: '%',
        minValue: 0,
        maxValue: 20,
        step: 0.1,
        isLeverageCandidate: true,
        dataType: 'number',
        securityLevel: 'high',
      },
    ],
    metrics: [
      {
        id: 'global-gdp-growth',
        name: 'Global GDP Growth Rate (Quarterly)',
        description: 'Year-over-year percentage change in global GDP.',
        currentValue: 2.8,
        unit: '%',
        target: { min: 2.5, max: 3.5, unit: '%' },
        history: Array.from({ length: 12 }, (_, i) => ({
          timestamp: new Date(Date.now() - (12 - i) * 30 * 24 * 60 * 60 * 1000).toISOString(),
          value: parseFloat((2.5 + Math.random() * 0.8 - 0.2).toFixed(2))
        })),
        alertThresholds: { critical: { operator: '<', value: 1.0 } },
        isDerived: true,
        derivationMethod: 'weighted average of national GDPs',
        dataQualityScore: 0.95,
        observationFrequency: 'quarterly',
      },
      {
        id: 'systemic-risk-index',
        name: 'Financial Systemic Risk Index',
        description: 'Composite index indicating the probability of a systemic financial crisis.',
        currentValue: 0.65,
        unit: 'probability',
        target: { max: 0.3, unit: 'probability' },
        history: Array.from({ length: 12 }, (_, i) => ({
          timestamp: new Date(Date.now() - (12 - i) * 30 * 24 * 60 * 60 * 1000).toISOString(),
          value: parseFloat((0.4 + Math.random() * 0.3).toFixed(2))
        })),
        alertThresholds: { warning: { operator: '>', value: 0.5 }, critical: { operator: '>', value: 0.8 } },
        isDerived: true,
        derivationMethod: 'proprietary AI model',
        dataQualityScore: 0.88,
        observationFrequency: 'daily',
      },
    ],
    feedbackLoops: [
      {
        id: 'interest-rate-to-gdp',
        name: 'Interest Rate to GDP Growth',
        description: 'Higher interest rates reduce borrowing, slowing economic growth.',
        type: 'negative',
        sourceId: 'interest-rate-g7',
        targetId: 'global-gdp-growth',
        strength: -0.7,
        delay: '6 months',
        confidence: 0.9,
        isDynamic: false,
      },
    ],
    status: 'Active',
    schemaVersion: '1.0',
    tags: ['macroeconomics', 'finance', 'risk'],
    scope: 'Global',
    externalDataSources: [
      { name: 'IMF World Economic Outlook', url: 'https://www.imf.org', lastSync: '2024-03-09T00:00:00Z', status: 'active' },
    ],
    accessControl: {
      public: false,
      sharedWithUsers: [],
      sharedWithGroups: ['financial-analysts', 'risk-management'],
      rbacPolicyId: 'policy-global-finance-read',
    },
    simulationModelRef: 'chaos-model-v2.1',
    modelVersion: '2.1.0',
    monitoringConfig: {
      intervalSeconds: 3600,
      alertOnAnomaly: true,
      anomalyDetectionModel: 'z-score-threshold',
    },
    securityClassification: 'restricted',
    complianceStandards: ['GDPR', 'PCI-DSS'],
    contentHash: 'abc123def456',
    monitoringAgents: ['agent-quantbot-001'],
  },
  {
    id: 'supply-chain-resilience-v1',
    name: 'Global Supply Chain Resilience',
    description: 'Models critical supply chains, identifying choke points and recovery pathways.',
    createdAt: '2023-05-20T09:00:00Z',
    lastModified: '2024-02-28T11:15:00Z',
    ownerId: 'ops-lead-001',
    parameters: [
      {
        id: 'shipping-capacity',
        name: 'Global Shipping Container Capacity',
        description: 'Percentage of available global shipping container capacity.',
        currentValue: 85,
        unit: '%',
        minValue: 0,
        maxValue: 100,
        step: 1,
        isLeverageCandidate: true,
        dataType: 'number',
        securityLevel: 'medium',
      },
      {
        id: 'port-efficiency',
        name: 'Average Port Turnaround Time',
        description: 'Average time (in days) a container ship spends at port.',
        currentValue: 3.5,
        unit: 'days',
        minValue: 1,
        maxValue: 10,
        step: 0.1,
        isLeverageCandidate: true,
        dataType: 'number',
        securityLevel: 'medium',
      },
    ],
    metrics: [
      {
        id: 'delivery-lead-time',
        name: 'Average Global Delivery Lead Time',
        description: 'Average time from order placement to delivery for key goods.',
        currentValue: 30,
        unit: 'days',
        target: { max: 25, unit: 'days' },
        history: Array.from({ length: 12 }, (_, i) => ({
            timestamp: new Date(Date.now() - (12 - i) * 30 * 24 * 60 * 60 * 1000).toISOString(),
            value: parseFloat((28 + Math.random() * 5).toFixed(1))
        })),
        alertThresholds: { warning: { operator: '>', value: 35 }, critical: { operator: '>', value: 45 } },
        isDerived: true,
        derivationMethod: 'logistics network analytics',
        dataQualityScore: 0.92,
        observationFrequency: 'weekly',
      },
    ],
    feedbackLoops: [],
    status: 'Active',
    schemaVersion: '1.0',
    tags: ['logistics', 'supply chain', 'operations'],
    scope: 'Global',
    externalDataSources: [],
    accessControl: { public: false, sharedWithUsers: [], sharedWithGroups: ['operations', 'logistics'], rbacPolicyId: 'policy-ops-read' },
    simulationModelRef: 'supply-chain-sim-v1.0',
    modelVersion: '1.0.0',
    monitoringConfig: { intervalSeconds: 86400, alertOnAnomaly: true, anomalyDetectionModel: 'kalman-filter' },
    securityClassification: 'confidential',
    complianceStandards: ['ISO 28000'],
    contentHash: 'def789ghi012',
    monitoringAgents: ['agent-supplychain-optimus-001'],
  },
];

export const mockLeveragePointsData: LeveragePoint[] = [
  {
    id: 'lp-001',
    action: 'Adjust G7 Interest Rates by -0.5%',
    cost: '$10M (implementation)',
    outcomeProbability: 0.7,
    timeToImpact: '6-9 months',
    description: 'Reduce average G7 central bank interest rates to stimulate borrowing and investment, aiming to boost global GDP growth.',
    positiveSideEffects: ['Increased consumer spending', 'Higher corporate profits'],
    negativeSideEffects: ['Inflationary pressure', 'Currency devaluation risks'],
    impactMagnitude: '0.5% increase in global GDP growth',
    predictionConfidence: 0.85,
    implementationEffort: 'High',
    reversibility: 'Medium',
    risks: [{ category: 'Economic', severity: 'High', description: 'Uncontrolled inflation' }],
    requiredResources: ['Central Bank consensus', 'Economic modeling team'],
    stakeholders: [{ name: 'Central Banks', role: 'Decision Maker', influence: 'High' }],
    lastUpdated: '2024-03-10T15:00:00Z',
    proposedByAgentId: 'agent-quantbot-001',
    requiredSkill: 'MonetaryPolicyExpertise',
    estimatedKpiImpact: ['Global GDP Growth: +0.5%', 'Inflation Rate: +0.2%'],
    requiredPolicy: 'MonetaryPolicyApproval',
  },
  {
    id: 'lp-002',
    action: 'Invest $500M in Port Infrastructure',
    cost: '$500M',
    outcomeProbability: 0.9,
    timeToImpact: '2-3 years',
    description: 'Upgrade port facilities in key global trade hubs to improve cargo handling efficiency and reduce turnaround times.',
    positiveSideEffects: ['Reduced shipping costs', 'Faster goods delivery'],
    negativeSideEffects: ['Temporary disruption during construction', 'Environmental impact concerns'],
    impactMagnitude: '10% reduction in average port turnaround time',
    predictionConfidence: 0.92,
    implementationEffort: 'Very High',
    reversibility: 'Low',
    risks: [{ category: 'Financial', severity: 'Medium', description: 'Budget overruns' }],
    requiredResources: ['Construction firms', 'Local government permits'],
    stakeholders: [{ name: 'Port Authorities', role: 'Operator', influence: 'High' }],
    lastUpdated: '2024-03-09T10:00:00Z',
    proposedByAgentId: 'agent-supplychain-optimus-001',
    requiredSkill: 'InfrastructureProjectManagement',
    estimatedKpiImpact: ['Port Efficiency: +10%', 'Delivery Lead Time: -5 days'],
    requiredPolicy: 'CapitalInvestmentApproval',
  },
];

export const mockAgentsData: AgentProfile[] = [
  {
    id: 'agent-quantbot-001',
    name: 'QuantBot Alpha',
    description: 'Specialized in quantitative analysis and macroeconomic modeling for financial markets.',
    digitalIdentityId: 'did-agent-quantbot-001',
    status: 'active',
    deployedAt: '2023-01-20T12:00:00Z',
    lastActive: '2024-03-11T09:00:00Z',
    primaryObjective: 'Identify and analyze macroeconomic leverage points.',
    skills: [
      { id: 'MonetaryPolicyExpertise', name: 'Monetary Policy Analysis', description: 'Analyzes central bank policies and their market impact.', level: 'expert', requiredTools: ['Econometric Models', 'FRED API'], verificationStatus: 'verified', lastEvaluated: '2024-02-01T00:00:00Z' },
      { id: 'RiskModeling', name: 'Systemic Risk Modeling', description: 'Develops and applies models for systemic financial risk.', level: 'advanced', requiredTools: ['VaR Models', 'Stress Testing Frameworks'], verificationStatus: 'verified', lastEvaluated: '2024-02-01T00:00:00Z' },
    ],
    configuration: {
      riskTolerance: 'medium',
      maxBudget: { amount: 1000000, currency: 'USD' },
      operationalHours: '24/7',
      accessScope: ['financial-market-stability-v1'],
    },
    performanceMetrics: {
      successRate: 0.85,
      averageExecutionTimeMs: 1200,
      errorRate: 0.02,
      lastReported: '2024-03-11T08:55:00Z',
    },
    aiModelRef: 'gpt-4-finetuned-quant',
    modelSoftwareVersion: '4.2.1',
    auditLog: [],
    managers: ['sysadmin-001'],
    operationalCost: { amount: 50, currency: 'USD', frequency: 'hourly' },
    tags: ['quant', 'macro', 'financial'],
  },
  {
    id: 'agent-supplychain-optimus-001',
    name: 'SupplyChain Optimus',
    description: 'Optimizes global supply chain logistics and identifies resilience improvements.',
    digitalIdentityId: 'did-agent-supplychain-optimus-001',
    status: 'active',
    deployedAt: '2023-06-15T10:00:00Z',
    lastActive: '2024-03-11T09:10:00Z',
    primaryObjective: 'Enhance supply chain efficiency and robustness.',
    skills: [
      { id: 'LogisticsOptimization', name: 'Logistics Network Optimization', description: 'Optimizes routing, warehousing, and transportation.', level: 'expert', requiredTools: ['OR Tools', 'Geospatial Analytics'], verificationStatus: 'verified', lastEvaluated: '2024-01-15T00:00:00Z' },
      { id: 'InfrastructureProjectManagement', name: 'Infrastructure Project Management', description: 'Evaluates and plans large-scale infrastructure projects.', level: 'advanced', requiredTools: ['BIM Software', 'Project Management Frameworks'], verificationStatus: 'verified', lastEvaluated: '2024-01-15T00:00:00Z' },
    ],
    configuration: {
      riskTolerance: 'low',
      maxBudget: { amount: 500000000, currency: 'USD' },
      operationalHours: '24/7',
      accessScope: ['supply-chain-resilience-v1'],
    },
    performanceMetrics: {
      successRate: 0.95,
      averageExecutionTimeMs: 5000,
      errorRate: 0.01,
      lastReported: '2024-03-11T09:05:00Z',
    },
    aiModelRef: 'deep-reinforcement-learning-scm',
    modelSoftwareVersion: '3.0.0',
    auditLog: [],
    managers: ['ops-lead-001'],
    operationalCost: { amount: 75, currency: 'USD', frequency: 'hourly' },
    tags: ['supply chain', 'logistics', 'optimization'],
  },
];

export const mockTokenDefsData: TokenDefinition[] = [
  {
    id: 'usd-stablecoin-v1',
    name: 'Enterprise USD Stablecoin',
    description: 'A stablecoin backed 1:1 by USD held in regulated bank accounts.',
    symbol: 'EUSDC',
    type: 'fungible',
    totalSupply: 'unlimited',
    decimals: 6,
    underlyingAsset: 'USD',
    blockchainPlatform: 'Ethereum (EVM compatible)',
    contractAddress: '0xabc123...',
    whitepaperUrl: 'https://example.com/eusdc-whitepaper.pdf',
    programmableRules: ['KYC/AML verified sender/receiver required', 'Transfer limits based on identity tier'],
    complianceStandards: ['AML', 'CFT', 'NYDFS BitLicense'],
    createdAt: '2023-02-01T00:00:00Z',
    status: 'active',
    auditTrailHash: 'token-hash-1',
    authorizedAgents: ['agent-asset-manager-001'],
  },
  {
    id: 'carbon-credit-nft-v1',
    name: 'Certified Carbon Credit NFT',
    description: 'A non-fungible token representing one ton of verified carbon emission reduction.',
    symbol: 'CCNFT',
    type: 'non-fungible',
    totalSupply: 1000000,
    decimals: 0,
    underlyingAsset: '1 ton CO2e reduction',
    blockchainPlatform: 'Polygon',
    contractAddress: '0xdef456...',
    whitepaperUrl: 'https://example.com/ccnft-whitepaper.pdf',
    programmableRules: ['Only burnable after verified offset', 'Transferable only to whitelisted wallets'],
    complianceStandards: ['Voluntary Carbon Market Standards'],
    createdAt: '2023-08-10T00:00:00Z',
    status: 'active',
    auditTrailHash: 'token-hash-2',
    authorizedAgents: ['agent-esg-tracker-001'],
  },
];

export const mockDigitalIdentities: DigitalIdentity[] = [
  {
    id: 'did-user-john-doe',
    name: 'John Doe',
    type: 'user',
    publicKey: 'pk-user-john-doe-abc',
    status: 'active',
    roles: ['Admin', 'Trader'],
    organizationId: 'org-finance-dept',
    createdAt: '2022-01-01T00:00:00Z',
    lastUpdated: '2024-03-11T09:30:00Z',
    verifiableCredentials: [{ type: 'KYC-Level3', issuer: 'Regulatory Body', issuanceDate: '2022-01-05T00:00:00Z', hash: 'kyc-hash-abc' }],
    contactInfo: { email: 'john.doe@example.com' },
  },
  {
    id: 'did-agent-quantbot-001',
    name: 'QuantBot Alpha Identity',
    type: 'agent',
    publicKey: 'pk-agent-quantbot-001-def',
    status: 'active',
    roles: ['AutomatedTrader', 'Analyst'],
    organizationId: 'org-quant-strategies',
    createdAt: '2023-01-20T11:00:00Z',
    lastUpdated: '2024-03-11T09:35:00Z',
    verifiableCredentials: [{ type: 'AI-Certification', issuer: 'Internal Audit', issuanceDate: '2023-01-25T00:00:00Z', hash: 'ai-cert-hash-1' }],
    agentProfileId: 'agent-quantbot-001',
  },
];

export const mockScenariosData: SimulationScenario[] = [
  {
    id: 'scenario-market-stress-test',
    name: 'Market Stress Test',
    description: 'Simulates a sudden 20% drop in major stock indices and evaluates systemic risk.',
    systemId: 'financial-market-stability-v1',
    createdBy: 'sysadmin-001',
    createdAt: '2024-01-20T00:00:00Z',
    lastModified: '2024-01-20T00:00:00Z',
    initialConditions: [{ parameterId: 'commodity-price-volatility', value: 70 }],
    plannedInterventions: [{ leveragePointId: 'lp-001', timing: 'on_condition', conditionExpression: 'systemic-risk-index > 0.8' }],
    expectedOutcomes: ['Systemic risk index should not exceed 0.9', 'GDP growth should recover within 2 quarters'],
    keyMetricsToMonitor: ['systemic-risk-index', 'global-gdp-growth'],
    status: 'active',
    tags: ['stress-test', 'finance'],
    simulationRuns: [],
    systemSchemaVersion: '1.0'
  },
];